name = "xvc-interview"
main = "src/index.ts"
compatibility_date = "2024-06-01"

# Static assets
[assets]
directory = "./public"

# KV namespace for storing generation sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "c412e208afe041648d1694611a054db0"
